### ISSUE TITLE
Broken on 2.12.4

### ISSUE THREAD

**Issue by nafg** [tek/splain#13]
From a discussion on gitter.im/scala/contributors:

> nafg `@nafg` [October 31, 2017 10:14 PM](https://gitter.im/scala/contributors?at=59f92e05d6c36fca31bf6999)
> I'm trying to use the tek/splain compiler plugin and it works fine with 2.12.3 but with 2.12.4 I get java.lang.NoClassDefFoundError: scala/reflect/internal/util/Statistics$
>
> Harrison Houghton `@hrhino` [October 31, 2017 10:30 PM](https://gitter.im/scala/contributors?at=59f931c35a1758ed0f73efc3)
> I think jvican removed that and redid the statistics infra.
tek might need to publish a 2.12.4+ version of the plugin 
>
> Jorge `@jvican` [November 2, 2017 4:54 AM](https://gitter.im/scala/contributors?at=59fadd5c32e080696e55a828)
> `@nafg`: `@hrhino` is correct. Statistics are no longer objects, they are in the compiler cake, so that's why you get that classloading issue. The issue here is that compiler plugins are often cross-compiled to the Scala partial version (2.10, 2.11, 2.12), when they should instead be cross-compiled to the full scala version (2.12.1, 2.12.2, 2.12.3, 2.12.4). The reason why this is the only reasonable way to do it is because the compiler API does not have any bincompat guarantees.

**Comment by tek** [comment]
I've released packages for patch versions, please verify!

**Comment by nafg** [comment]
Looks good, thanks!
